"""хз

Revision ID: 073537f6ed14
Revises: 4e8b1c801441
Create Date: 2025-08-01 21:54:36.456260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073537f6ed14'
down_revision: Union[str, Sequence[str], None] = '4e8b1c801441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_constraint(op.f('test_sessions_user_id_fkey'), 'test_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'test_sessions', 'users', ['user_id'], ['telegram_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('test_sessions_user_id_fkey'), 'test_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('test_sessions', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
