"""deleted ENUM in RoadSign class

Revision ID: 10314f611c69
Revises: cb6b8c601a70
Create Date: 2025-07-11 23:29:52.995349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10314f611c69'
down_revision: Union[str, Sequence[str], None] = 'cb6b8c601a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.add_column('road_signs', sa.Column('photo_id', sa.String(length=255), nullable=True))
    op.alter_column('road_signs', 'type',
               existing_type=postgresql.ENUM('WARNING', 'PROHIBITION', 'MANDATORY', 'PRIORITY', 'INFORMATION', 'SERVICE', 'ADDITIONAL', name='roadsign_type_enum'),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_column('road_signs', 'image_url')
    op.alter_column('users', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('road_signs', sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('road_signs', 'type',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('WARNING', 'PROHIBITION', 'MANDATORY', 'PRIORITY', 'INFORMATION', 'SERVICE', 'ADDITIONAL', name='roadsign_type_enum'),
               existing_nullable=False)
    op.drop_column('road_signs', 'photo_id')
    op.alter_column('admins', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
