"""хз

Revision ID: 4e8b1c801441
Revises: 5b36f1ff57b4
Create Date: 2025-08-01 21:46:31.922161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8b1c801441'
down_revision: Union[str, Sequence[str], None] = '5b36f1ff57b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('user_answer', sa.String(), nullable=False))
    op.drop_column('answers', 'user_choice')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('user_choice', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('answers', 'user_answer')
    # ### end Alembic commands ###
