"""Rename user_id to telegram_id in Admin, switch to BigInteger. Add username for models and handle exception IntegrityError

Revision ID: 69071ef5c0c8
Revises: 
Create Date: 2025-07-09 20:29:59.975574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69071ef5c0c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('telegram_id', sa.BigInteger(), nullable=False))
    op.add_column('admins', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.add_column('admins', sa.Column('username', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('admins_user_id_key'), 'admins', type_='unique')
    op.create_unique_constraint(None, 'admins', ['telegram_id'])
    op.drop_constraint(op.f('admins_user_id_fkey'), 'admins', type_='foreignkey')
    op.create_foreign_key(None, 'admins', 'users', ['telegram_id'], ['telegram_id'], ondelete='CASCADE')
    op.drop_column('admins', 'user_id')
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.add_column('admins', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.create_foreign_key(op.f('admins_user_id_fkey'), 'admins', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'admins', type_='unique')
    op.create_unique_constraint(op.f('admins_user_id_key'), 'admins', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('admins', 'username')
    op.drop_column('admins', 'full_name')
    op.drop_column('admins', 'telegram_id')
    # ### end Alembic commands ###
