"""changed field type in 'bot_info'

Revision ID: 8842a75eff2c
Revises: fdc59da7dc88
Create Date: 2025-08-15 17:54:29.174377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8842a75eff2c'
down_revision: Union[str, Sequence[str], None] = 'fdc59da7dc88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bot_info', 'text',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bot_info', 'text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
    # ### end Alembic commands ###
