"""Add position to SessionQuestion

Revision ID: 94ab478fd8dc
Revises: 5524fd0e7f95
Create Date: 2025-08-01 22:20:19.062789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ab478fd8dc'
down_revision: Union[str, Sequence[str], None] = '5524fd0e7f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_questions', sa.Column('position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_questions', 'position')
    # ### end Alembic commands ###
