"""add ready_for_delete to 'mistakes'

Revision ID: aaa376a193c8
Revises: da510444bae1
Create Date: 2025-08-14 12:01:23.702106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa376a193c8'
down_revision: Union[str, Sequence[str], None] = 'da510444bae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mistakes', sa.Column('ready_for_delete', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mistakes', 'ready_for_delete')
    # ### end Alembic commands ###
