"""Fix user_id at Answer

Revision ID: ab39a1d3e509
Revises: e2ba216bde53
Create Date: 2025-08-06 22:25:44.372908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab39a1d3e509'
down_revision: Union[str, Sequence[str], None] = 'e2ba216bde53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_constraint(op.f('answers_user_id_fkey'), 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'users', ['user_id'], ['telegram_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key(op.f('answers_user_id_fkey'), 'answers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('answers', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
