"""add field 'referral_code' to model 'User'

Revision ID: b7c1843443b8
Revises: 8842a75eff2c
Create Date: 2025-10-21 23:29:51.145373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c1843443b8'
down_revision: Union[str, Sequence[str], None] = '8842a75eff2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referral_code')
    # ### end Alembic commands ###
