"""deleted class Topic and upgraded any models

Revision ID: b83517f66b7d
Revises: 10314f611c69
Create Date: 2025-07-16 20:19:27.005984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83517f66b7d'
down_revision: Union[str, Sequence[str], None] = '10314f611c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Удаляем внешний ключ и колонку topic_id из questions
    op.drop_constraint('questions_topic_id_fkey', 'questions', type_='foreignkey')
    op.drop_column('questions', 'topic_id')

    # 2. Добавляем ticket_id
    op.add_column('questions', sa.Column('ticket_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'tickets', ['ticket_id'], ['id'])

    # 3. Теперь безопасно удаляем таблицу topics
    op.drop_table('topics')



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_topic_id_fkey'), 'questions', 'topics', ['topic_id'], ['id'])
    op.drop_column('questions', 'ticket_id')
    op.create_table('topics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('topics_pkey')),
    sa.UniqueConstraint('name', name=op.f('topics_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table(
        'topics',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.add_column('questions', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'questions_topic_id_fkey',
        'questions', 'topics',
        ['topic_id'], ['id']
    )

    # ### end Alembic commands ###
