"""add correct/incorrect answers to user

Revision ID: da510444bae1
Revises: ed4e458441ca
Create Date: 2025-08-13 21:13:49.362628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da510444bae1'
down_revision: Union[str, Sequence[str], None] = 'ed4e458441ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('correct_answers', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('incorrect_answers', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'incorrect_answers')
    op.drop_column('users', 'correct_answers')
    # ### end Alembic commands ###
