"""add 'mistake_count' to 'TestSession'

Revision ID: dad8781ba20e
Revises: aaa376a193c8
Create Date: 2025-08-14 16:52:07.864046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad8781ba20e'
down_revision: Union[str, Sequence[str], None] = 'aaa376a193c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_sessions', sa.Column('mistake_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_sessions', 'mistake_count')
    # ### end Alembic commands ###
