"""upgraded class Questions

Revision ID: dd2c1b0dd07c
Revises: b83517f66b7d
Create Date: 2025-07-24 21:36:08.102761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd2c1b0dd07c'
down_revision: Union[str, Sequence[str], None] = 'b83517f66b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_number', sa.Integer(), nullable=False))
    op.add_column('questions', sa.Column('correct_answer', sa.String(), nullable=False))
    op.add_column('questions', sa.Column('photo_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'questions', ['question_number'])
    op.drop_column('questions', 'is_active')
    op.drop_column('questions', 'image_url')
    op.drop_column('questions', 'correct_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('correct_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_column('questions', 'photo_id')
    op.drop_column('questions', 'correct_answer')
    op.drop_column('questions', 'question_number')
    # ### end Alembic commands ###
