"""Added selected_answer to session_questions

Revision ID: e0c278d5f65f
Revises: ab39a1d3e509
Create Date: 2025-08-07 21:04:41.498905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c278d5f65f'
down_revision: Union[str, Sequence[str], None] = 'ab39a1d3e509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_questions', sa.Column('selected_answer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_questions', 'selected_answer')
    # ### end Alembic commands ###
