"""Fix Answer and Mistake models

Revision ID: e2ba216bde53
Revises: 01f67a4efae1
Create Date: 2025-08-06 22:18:37.617076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2ba216bde53'
down_revision: Union[str, Sequence[str], None] = '01f67a4efae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'answers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('mistakes', 'times_failed')
    op.drop_column('mistakes', 'last_failed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mistakes', sa.Column('last_failed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('mistakes', sa.Column('times_failed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_column('answers', 'user_id')
    # ### end Alembic commands ###
