"""Updated Mistake and TestSession

Revision ID: ed4e458441ca
Revises: e0c278d5f65f
Create Date: 2025-08-08 13:30:05.022121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed4e458441ca'
down_revision: Union[str, Sequence[str], None] = 'e0c278d5f65f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mistakes', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_constraint(op.f('mistakes_user_id_fkey'), 'mistakes', type_='foreignkey')
    op.create_foreign_key(None, 'mistakes', 'users', ['user_id'], ['telegram_id'], ondelete='CASCADE')
    op.alter_column('saved_questions', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_constraint(op.f('saved_questions_user_id_fkey'), 'saved_questions', type_='foreignkey')
    op.create_foreign_key(None, 'saved_questions', 'users', ['user_id'], ['telegram_id'], ondelete='CASCADE')
    op.add_column('test_sessions', sa.Column('ticket_number', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('test_sessions_source_ticket_id_fkey'), 'test_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'test_sessions', 'tickets', ['ticket_number'], ['number'])
    op.drop_column('test_sessions', 'source_ticket_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_sessions', sa.Column('source_ticket_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'test_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('test_sessions_source_ticket_id_fkey'), 'test_sessions', 'tickets', ['source_ticket_id'], ['id'])
    op.drop_column('test_sessions', 'ticket_number')
    op.drop_constraint(None, 'saved_questions', type_='foreignkey')
    op.create_foreign_key(op.f('saved_questions_user_id_fkey'), 'saved_questions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('saved_questions', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'mistakes', type_='foreignkey')
    op.create_foreign_key(op.f('mistakes_user_id_fkey'), 'mistakes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('mistakes', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
