"""Add started_at to test_sessions

Revision ID: fbecd5ad6d4d
Revises: bef5d485e0cd
Create Date: 2025-08-06 15:43:19.628622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbecd5ad6d4d'
down_revision: Union[str, Sequence[str], None] = 'bef5d485e0cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('answers', sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('mistakes', sa.Column('last_failed_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('saved_questions', sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('test_sessions', sa.Column('started_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('users', sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'joined_at')
    op.drop_column('test_sessions', 'started_at')
    op.drop_column('saved_questions', 'saved_at')
    op.drop_column('mistakes', 'last_failed_at')
    op.drop_column('answers', 'answered_at')
    op.drop_column('admins', 'created_at')
    # ### end Alembic commands ###
